open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let myclib_init =
    foreign "myclib_init" (string @-> returning Types.myclib_ctx_t)

  let myclib_done = foreign "myclib_done" (Types.myclib_ctx_t @-> returning void)

  let myclib_get_name =
    foreign "myclib_get_name" (Types.myclib_ctx_t @-> returning string)
  (* 
/// do not free returned pointer!
const char* myclib_get_name(myclib_ctx_t *ctx);
void myclib_done(myclib_ctx_t *ctx);
 *)
end
