# need to test
# 1) fully generated program from some template files
# 2) template files dependencies (template A depends on B which is
# discovered while processing template A)

# Solution:
# 1) fixed CMakeLists.txt file
#   set(templates_src a.templ b.templ)
#   set(templates_gen_c TODO convert ${templates_src} to *.c files)
# 2) generated templates_deps.txt which is included by CMakeLists
#   created empty on first run.
#   on consecutive runs generated by template processor invocation:
#   add_custom_command(OUTPUT 
#   //add_custom_target(templates SOURCES ${templates_src})
#   add_dependency(a.templ b.templ)
#   

# so what we need:
# a separate build system that regenerates processed files
