// initially generated by gemini 3.7 flash

import std.stdio;
import std.process : execute;
import std.json;
import std.algorithm : canFind, filter;
import std.array : empty;
import std.string : strip;

struct ActionPlan {
    string[] mountpoints;
    string[] cryptoDevicesToLock;
}

void collectActions(JSONValue node, ref ActionPlan plan) {
    // Collect active mountpoints (handles both string and array formats across lsblk versions)
    if ("mountpoints" in node && node["mountpoints"].type == JSONType.array) {
        foreach (mp; node["mountpoints"].array) {
            if (mp.type == JSONType.string && mp.str.length > 0 && mp.str != "null") {
                plan.mountpoints ~= mp.str;
            }
        }
    } else if ("mountpoint" in node && node["mountpoint"].type == JSONType.string) {
        string mp = node["mountpoint"].str;
        if (mp.length > 0 && mp != "null") {
            plan.mountpoints ~= mp;
        }
    }

    // Identify encrypted containers (LUKS/crypt) that require locking
    if ("type" in node && node["type"].type == JSONType.string) {
        if (node["type"].str == "crypt") {
            string devName = "name" in node ? node["name"].str : "unknown";
            plan.cryptoDevicesToLock ~= "/dev/mapper/" ~ devName;
        }
    }

    // Recursively check child partitions and volume mappings
    if ("children" in node && node["children"].type == JSONType.array) {
        foreach (child; node["children"].array) {
            collectActions(child, plan);
        }
    }
}

void main() {
    // Run lsblk requesting JSON output with the required attributes
    auto res = execute(["lsblk", "-J", "-o", "NAME,PATH,TYPE,MOUNTPOINT,MOUNTPOINTS,HOTPLUG,RM,MODEL,SIZE"]);
    
    if (res.status != 0) {
        stderr.writeln("Failed to execute lsblk. Error:\n", res.output);
        return;
    }

    JSONValue root;
    try {
        root = parseJSON(res.output);
    } catch (JSONException e) {
        stderr.writeln("Failed to parse lsblk JSON: ", e.msg);
        return;
    }

    if (!("blockdevices" in root) || root["blockdevices"].type != JSONType.array) {
        writeln("No block devices detected.");
        return;
    }

    writeln("=== Storage Devices Safe Removal & Power-off Inspection ===\n");

    foreach (dev; root["blockdevices"].array) {
        string devPath = "path" in dev ? dev["path"].str : ("name" in dev ? "/dev/" ~ dev["name"].str : "unknown");
        string devType = "type" in dev ? dev["type"].str : "unknown";
        string model   = "model" in dev && dev["model"].type == JSONType.string ? dev["model"].str.strip : "Generic";
        string size    = "size" in dev && dev["size"].type == JSONType.string ? dev["size"].str : "";

        // Only inspect root-level physical drives (disk, loop, etc.)
        if (devType != "disk" && devType != "loop") {
            continue;
        }

        ActionPlan plan;
        collectActions(dev, plan);

        writefln("Device: %s [%s, %s] (%s)", devPath, model, size, devType);

        if (plan.mountpoints.empty && plan.cryptoDevicesToLock.empty) {
            writeln("  Status: Ready to power off directly.");
            writefln("  Command: udisksctl power-off -b %s\n", devPath);
            continue;
        }

        writeln("  Status: Active dependencies detected.");

        if (!plan.mountpoints.empty) {
            writeln("  Required Unmounts:");
            foreach (mp; plan.mountpoints) {
                writefln("    - umount %s   (or: udisksctl unmount -p ...)", mp);
            }
        }

        if (!plan.cryptoDevicesToLock.empty) {
            writeln("  Required Crypto Locks:");
            foreach (cdev; plan.cryptoDevicesToLock) {
                writefln("    - udisksctl lock -b %s", cdev);
            }
        }

        writefln("  Final step: udisksctl power-off -b %s\n", devPath);
    }
}
